### ISSUE TITLE
Image Focus Not Working

### ISSUE THREAD

**Issue by asvensen** [CuBoulder/tiamat-theme#1279]
I've edited several images in the media library on the /civic-engagment site to reset the focal point of the image and that change is not reflected on the front end. It worked on 1 of 3 images I edited, but not the other two. If you look to the "In the News" block on https://www.colorado.edu/civic-engagement, the left most and center images are not showing the change, but the right most image is. I've rebuilt the cache, checked that my edit took, and hit shift + refresh several times and the change doesn't show.

**Comment by jnicholCU** [comment]
This is part of the image styling rework I am currently doing. I'll add this issue to my list of images needing restyled.

**Comment by jnicholCU** [comment]
Duplicate #1249

**Comment by jnicholCU** [comment]
This one should be fixed in from https://github.com/CuBoulder/tiamat-custom-entities/pull/171

**Comment by asvensen** [comment]
Hey @jnicholCU! The image focus is still not working on https://www.colorado.edu/civic-engagement/. I just went in and edited two of the photos showing in the bottom content grid on that page (the left most image and the middle image) and the changes are not showing. I refreshed the browser, etc. And then I did it again putting the focus in a really obviously crazy spot and again nothing happened.

**Comment by jnicholCU** [comment]
Ah sorry @asvensen I should have been more clear with my response. The fix has been merged into our release pool but doesn't look like it's been pushed out yet.

**Comment by asvensen** [comment]
Ah! That makes sense. I appreciate it!

--
Annie Svensen
Senior User Experience Designer & Information Architect
Strategic Relations & Communications
University of Colorado Boulder
Boulder, Colorado 80309


From: Joshua Nicholson ***@***.***>
Date: Monday, September 16, 2024 at 9:00 AM
To: CuBoulder/tiamat-theme ***@***.***>
Cc: Annie Svensen ***@***.***>, Mention ***@***.***>
Subject: Re: [CuBoulder/tiamat-theme] Image Focus Not Working (Issue #1279)
[External email - use caution]


Ah sorry @asvensen<https://github.com/asvensen> I should have been more clear with my response. The fix has been merged into our release pool but doesn't look like it's been pushed out yet.
